import type { Credit } from "./types";

export const credits: Credit[] = [
  {
    id: "c1",
    name: "CETP Methane Abatement 2024",
    type: "Carbon",
    issuer: "KarbonLedger",
    region: "Maharashtra, IN",
    priceUsd: 12,
    available: 50000,
    vintage: 2024,
    methodology: "IPCC Tier 2",
    sdgs: ["SDG6", "SDG13"],
    summary: "Avoided methane emissions from wastewater treatment upgrades across CETP clusters.",
    rating: 4.6,
  },
  {
    id: "c2",
    name: "Effluent BOD Reduction Bundle",
    type: "Water",
    issuer: "GreenFlow Alliance",
    region: "Gujarat, IN",
    priceUsd: 9,
    available: 80000,
    vintage: 2023,
    methodology: "BOD/COD verified reductions",
    sdgs: ["SDG6"],
    summary: "Measured BOD/COD reductions through process optimization and biological treatment.",
    rating: 4.2,
  },
  {
    id: "c3",
    name: "Sludge-to-Energy Credit Lot",
    type: "Carbon",
    issuer: "BlueCarbon Labs",
    region: "Tamil Nadu, IN",
    priceUsd: 15,
    available: 36000,
    vintage: 2024,
    methodology: "Waste-to-energy displacement",
    sdgs: ["SDG7", "SDG13"],
    summary: "Biogas generation displacing grid electricity with documented metering.",
    rating: 4.8,
  },
  {
    id: "c4",
    name: "Nutrient Load Reduction Series",
    type: "Water",
    issuer: "KarbonLedger",
    region: "Karnataka, IN",
    priceUsd: 11,
    available: 42000,
    vintage: 2023,
    methodology: "TN/TP reductions verified",
    sdgs: ["SDG6", "SDG14"],
    summary: "Nitrogen and phosphorus reductions via advanced tertiary treatment.",
    rating: 4.3,
  },
  {
    id: "c5",
    name: "Fugitive Emissions Capture",
    type: "Carbon",
    issuer: "EcoMeasure",
    region: "Rajasthan, IN",
    priceUsd: 18,
    available: 20000,
    vintage: 2025,
    methodology: "Flaring + capture verified",
    sdgs: ["SDG9", "SDG13"],
    summary: "Capture and flare of fugitive emissions from aeration basins.",
    rating: 4.5,
  },
  {
    id: "c6",
    name: "Groundwater Recharge Credits",
    type: "Water",
    issuer: "HydroTrust",
    region: "Uttar Pradesh, IN",
    priceUsd: 8,
    available: 95000,
    vintage: 2024,
    methodology: "Recharge volume metering",
    sdgs: ["SDG6", "SDG15"],
    summary: "Managed aquifer recharge with telemetry and independent verification.",
    rating: 4.0,
  },
];
